home_page:
    path:  /
    defaults: { _controller: "AkjnBundle:Login:login" }

_index:
    pattern: /panel
    defaults: { _controller: "AdminBundle:Default:mainRedirect" }

masters:
    resource: "masters.yml"
    prefix:  /masters
    
students:
    resource: "students.yml"
    prefix:  /students
    
attendence:
    resource: "attendence.yml"
    prefix:  /attendence