<?php

namespace AdminBundle\Repository;

/**
 * ClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassRoomRepository extends \Doctrine\ORM\EntityRepository {
    
}
