<?php

namespace AdminBundle\Repository;

/**
 * MasterStudentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MasterStudentsRepository extends \Doctrine\ORM\EntityRepository
{
}
