<?php

namespace AdminBundle\Repository;

/**
 * SubjectClassLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectClassLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
