<?php

namespace AdminBundle\Repository;

/**
 * twelfth_attendenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class twelfth_attendenceRepository extends \Doctrine\ORM\EntityRepository
{
}
