  
akjn_secured_login_registration:
    resource: "@AkjnBundle/Resources/config/routing/registration.yml"
    prefix:   /registration
    
akjn_secured_login:
    resource: "@AkjnBundle/Resources/config/routing/login.yml"
    prefix: /akjnusr
    
akjn_secured_user_reset:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.yml"
    prefix:   /resetting